# Generated by Django 5.2.8 on 2025-11-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_special",
            field=models.BooleanField(default=False, verbose_name="محصول ویژه"),
        ),
    ]
