# Generated by Django 5.2.8 on 2025-11-28 12:32

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_brand_options_specification_variant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True, editable=False, populate_from="name", unique=True
            ),
        ),
    ]
