# Generated by Django 5.2.8 on 2025-11-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, blank=True, max_length=220, unique=True
            ),
        ),
    ]
