# Generated by Django 5.2.8 on 2025-11-28 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_alter_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, blank=True, max_length=120, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, blank=True, max_length=120, unique=True
            ),
        ),
        migrations.CreateModel(
            name="ProductSlugHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_slug", models.SlugField(allow_unicode=True, max_length=220)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slug_history",
                        to="store.product",
                    ),
                ),
            ],
        ),
    ]
