# Generated by Django 5.2.8 on 2025-12-02 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_user_is_admin_user_groups_user_is_staff_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="default_profile_images.svg",
                null=True,
                upload_to="profile_image/",
            ),
        ),
    ]
